In [1]:
# (1). NumPy

# (2). Pandas

In [2]:
# Cell ==> Execute ==> Cntrl + Enter

# Cell ==> Execute the previous cell and create a new cell ==> Shift + Enter

In [3]:
# NumPy ==>  Numerical Python ==> It is a scintific Library

# List ==>  elements different -different dtypes ==> time consuming ==> not have more
# methods and functions

# NumPy ==> Elements ==> Array format ==> less time consuming and have more methods
#  and functions as compare to list .


In [4]:
# Python ==> 5% discover ==> contine research

In [5]:
import numpy as np

One Dimensional Array

In [6]:
a = [1,2,3,67,89]
type(a)

list

In [7]:
b = np.array(a)
b

array([ 1,  2,  3, 67, 89])

How to create a user defined Array

In [9]:
a = []
size = int(input("Enter size:"))
for i in range(size):
  val = int(input("Enter Number:"))
  a.append(val)

# print(a)
c = np.array(a)
c

Enter size:4
Enter Number:12333
Enter Number:53222
Enter Number:7888
Enter Number:9544


array([12333, 53222,  7888,  9544])

How to check size and dimension of an array ?

In [10]:
a = np.array([1,45,78,90])
a

array([ 1, 45, 78, 90])

In [17]:
print("Total Dimesion = " , a.ndim)
print("Shape of this array  = " , a.size)

Total Dimesion =  1
Shape of this array  =  4


In [18]:
a = [[1,2,3] , [4,5,6] , [7,8,9]]
b=  np.array(a)
b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
print("Total Dimesion = " , b.ndim)
print("Shape of this array  = " , b.shape)
print("Total Elements in this array = " , b.size)

Total Dimesion =  2
Shape of this array  =  (3, 3)
Total Elements in this array =  9


Total Elements = n(rows) * n(columns)

In [24]:
# NumPy Functions

In [25]:
# Images ==> pixels format ==> ppi (pixel per inch)

# 0 px ==> Complete Black

# 255 px ==> Complete white

# Images Gray Scale ==> 127.5

# Normalize ==> 0-1 (minimum pixel value = 0 , maximum pixel value = 1)

(1). zeros() ==> This function creates an array (either one dimensional or multi-dimensional) and fill all the values with zero .

In [26]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [30]:
a.size

5

In [31]:
b = np.zeros((2,3))
b

array([[0., 0., 0.],
       [0., 0., 0.]])

(2). Ones() ==> This function creates an array (either one dimensional or multi dimensional) and fill all the values with one .

In [32]:
a = np.ones(5)
a

array([1., 1., 1., 1., 1.])

In [33]:
b = np.ones((2,3))
b

array([[1., 1., 1.],
       [1., 1., 1.]])

(3). eye() ==> This function creates an array with all the digonal elements as 1 and rest all are 0 (In Square matrix). In Non-Square matrix the values are still one for digonal elements and rest all are zero .

In [34]:
# Square matrix ===> n(rows) = n(columns)
# Non-square Matrix ==> n(rows) != n(columns)

In [38]:
import numpy as np

In [36]:
a = np.eye(3,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [37]:
a = np.eye(4,4)
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

(4). diag() ==> This function creates an array in which we can pass custom array on digonal position and rest all are zero .

In [39]:
a = np.array([45,78,90,233])
a

array([ 45,  78,  90, 233])

In [40]:
np.diag(a)

array([[ 45,   0,   0,   0],
       [  0,  78,   0,   0],
       [  0,   0,  90,   0],
       [  0,   0,   0, 233]])

(5). Random Module ==>

(a). Randint() ==> It is used to generate random number between a given range .

syntax : np.random.randint(min_value , max_value , total_numbers)

(b). Rand() ==> It is used to generate random numbers between 0 to 1 .

syntax : np.random.rand(number of values)

(c). Randn() ==> It is used to generate random numbers between -7 to +7 .

syntax : np.random.randn(number of values)

In [60]:
a = np.random.randint(1,10,3)
a

array([3, 3, 1])

In [47]:
b = np.random.rand(5)
b

array([0.22567609, 0.51231196, 0.0450659 , 0.06088947, 0.32573889])

In [50]:
c = np.random.randn(4)
c

array([-1.31982506, -0.2114556 , -1.80212788, -0.33039156])

Reshaping Data

n(rows) * n(columns) = n(Total_Elements)

n(rows) = n(Total_Elements)/n(columns)

n(columns) = n(Total_Elements)/n(rows)

In [51]:
a = np.random.randint(1,50,12)
a

array([44, 29, 31, 41, 29, 45, 35, 33, 38,  6, 42,  5])

In [52]:
a.shape

(12,)

In [53]:
# 1*12 , 12*1

# 2*6 , 6*2

# 3*4 , 4*3

In [54]:
a.reshape(2,6)

array([[44, 29, 31, 41, 29, 45],
       [35, 33, 38,  6, 42,  5]])

In [55]:
a.reshape(6,2)

array([[44, 29],
       [31, 41],
       [29, 45],
       [35, 33],
       [38,  6],
       [42,  5]])

In [56]:
a.reshape(3,4)

array([[44, 29, 31, 41],
       [29, 45, 35, 33],
       [38,  6, 42,  5]])

In [57]:
a.reshape(4,3)

array([[44, 29, 31],
       [41, 29, 45],
       [35, 33, 38],
       [ 6, 42,  5]])

In [59]:
a.reshape(3,4)

array([[44, 29, 31, 41],
       [29, 45, 35, 33],
       [38,  6, 42,  5]])

Data ==> shift+ enter ==> randomly update ==> dataset (dummy data create random module) ==> model performance 80-90% ==> but shift + enter (refresh) ==> data update ==> Performance 60-70%

seed() ==> It will fix our random data .

In [75]:
np.random.seed(20)
a = np.random.randint(1,10,3)
a

array([4, 5, 7])

View Vs Copy ==>

In [78]:
a = np.array([10,20,30,40,50,60,70,80])
b=  a[3:6]  #3,4,5 indexed element = 40,50,60
b[:] = 0
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [79]:
a = np.array([10,20,30,40,50,60,70,80])
b = a[3:6].copy()
b[:] = 0
a

array([10, 20, 30, 40, 50, 60, 70, 80])

Conditional Selection in Numpy

In [80]:
a = np.arange(1,16)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [81]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True,  True])

In [82]:
b = a>10
a[b]

array([11, 12, 13, 14, 15])

In [83]:
a[a%2==0]

array([ 2,  4,  6,  8, 10, 12, 14])

Operations on Array

In [84]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [85]:
a+2

array([3, 4, 5, 6])

In [86]:
a**2

array([ 1,  4,  9, 16])

In [87]:
a = np.array([1,2,3,4]).reshape(2,2)
b = np.array([5,6,7,8]).reshape(2,2)


In [88]:
a

array([[1, 2],
       [3, 4]])

In [89]:
b

array([[5, 6],
       [7, 8]])

In [90]:
a+b

array([[ 6,  8],
       [10, 12]])

In [91]:
a-b

array([[-4, -4],
       [-4, -4]])

In [92]:
# matrix ==> multiply  ==> 1 matrix n(column) = 2 matrix n(rows)

In [93]:
a.dot(b)  # dot() returns matrix multiplication of 2 matrix .

array([[19, 22],
       [43, 50]])

In [94]:
a

array([[1, 2],
       [3, 4]])

In [95]:
np.min(a)

1

In [96]:
np.max(a)

4

In [97]:
np.argmin(a)

0

In [98]:
np.argmax(a)

3

In [99]:
np.sqrt(a)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [100]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [101]:
np.cos(a)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

np.unique(arr , return_index = True , return_counts = True)

returns 3 array .

(1). The array with unique values .
(2). The array with respective index value .
(3). The array with counting of frequency .

In [102]:
a = np.array([10,20,20,30,20,30,40,50,40,40,50,50,50,50,60,70])
np.unique(a , return_index = True , return_counts = True)

(array([10, 20, 30, 40, 50, 60, 70]),
 array([ 0,  1,  3,  6,  7, 14, 15]),
 array([1, 3, 2, 3, 5, 1, 1]))

In [104]:
# Horizontal And Vertical Stacking

In [108]:
a = np.array([1,2,3,4])
b=  np.array([5,6,7,8])
c = np.array([9,10,11,12])

In [109]:
np.hstack((a,b,c))

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [110]:
np.vstack((a,b,c))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Q.1  Write statement to import NumPy ?


Q.2 Create an array of 10 random integers ?


Q.3 Create an array in which elements are from 10 - 20 ?


Q.4 Create an array which contain values 5 , 10 times ?


Q.6 Create a one dimensional array and convert it into 3*3 matrix ?


Q.7 Create an array of size 3*3 but all the elements should between 0 to 1 ?

In [111]:
# step-1  Instant Data Scraper ==> Install this extension

# step-2 Go to Flipkart ==> Mobiles ==>click on  extension ==>
# click on Instant Data Scraper==> csv or xlsx copy ==> select csv ==> download (local system)

# ==> Open in excel  ==> modification

In [ ]:
# Pandas ==> Project ==>upload on Github